name: Deploy to EC2

on:
  push:
    branches:
      - master  # change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.0.0'

      # Install dependencies and build (if applicable)
      - name: Install Dependencies and Build
        run: |
          npm install
          # Add any build commands if your project requires it
          npm run build --modern

      # Deploy to EC2 instance
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 instance public IP or DNS name
          username: ${{ secrets.EC2_USERNAME }}  # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key
          source: "."  # Path to your project files to deploy
          target: "/home/ubuntu/web"  # Remote path where to deploy

      # SSH into EC2 instance and restart PM2
      - name: SSH into EC2 and restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/app

